# Generated by Django 2.0 on 2017-12-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usr', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=10)),
                ('birth', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
