# Generated by Django 2.0 on 2018-01-13 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebappImg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebappLoc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sheng', models.CharField(blank=True, max_length=8, null=True)),
                ('shi', models.CharField(max_length=8)),
                ('xiang', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='WebappNews',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=30)),
                ('flag', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WebappShoping',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('loc', models.CharField(max_length=30)),
                ('flag', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WebappUsr',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usr', models.CharField(max_length=30, unique=True)),
                ('passwd', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=10)),
                ('birth', models.CharField(max_length=30)),
                ('wx', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('loc', models.TextField()),
                ('infold', models.TextField(blank=True, null=True)),
                ('img', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='webappshoping',
            name='usr',
            field=models.ForeignKey(db_column='usr', on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.WebappUsr'),
        ),
        migrations.AddField(
            model_name='webappnews',
            name='usr',
            field=models.ForeignKey(db_column='usr', on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.WebappUsr'),
        ),
        migrations.AddField(
            model_name='webappimg',
            name='usr',
            field=models.ForeignKey(db_column='usr', on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.WebappUsr'),
        ),
    ]
